# Generated by Django 4.1.7 on 2023-04-08 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams_app', '0002_alter_attendancelog_scan_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='scan_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='attendance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ams_app.attendancelog'),
        ),
    ]
