# Generated by Django 4.1.7 on 2023-04-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams_app', '0005_remove_students_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='scan_time',
            field=models.DateTimeField(),
        ),
    ]
