# Generated by Django 4.1.7 on 2023-04-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams_app', '0006_alter_attendancelog_scan_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationstudent',
            name='student',
        ),
        migrations.AlterField(
            model_name='leavereportstaff',
            name='leave_status',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_status',
            field=models.IntegerField(default=False),
        ),
        migrations.DeleteModel(
            name='NotificationStaffs',
        ),
        migrations.DeleteModel(
            name='NotificationStudent',
        ),
    ]
